### ISSUE TITLE
UI profile: Pocket

### ISSUE THREAD

**Issue by ghost** [TungstenVn/Gomoku#2]
![Screenshot_20200414_085915_net zhuoweizhang mcpelauncher](https://user-images.githubusercontent.com/19583571/79192841-25734f80-7e32-11ea-8fe9-e4c9cc8b56bc.jpg)

if the picture doesn't explain it all, you only adjusted the plugin to work on Classic UI, while almost all the mcpe mobile players use Pocket UI .

**Comment by AngelliaX** [comment]
who still use pocket ui nowadays lul.However the pocket ui do depend on the screen size.

on my pc,the screen is large so when i use pocket ui, there are still 9 boxes on per row,but in my phone, it's 6.I dont know whether i should find a way to make the plugin work in this case or just simply changing to classic ui,it's better.

**Comment by ghost** [comment]
just add an option for the 3x3 to be selected as a classic or pocket ui

**Comment by ghost** [comment]
its the mostly used one
